### ISSUE TITLE
Release Tracker

### ISSUE THREAD

**Issue by nstilt1** [nstilt1/Plugin-Licensor-Open-Source-API-Methods#1]
These are the issues present that need to be fixed prior to release:

### Make a Private Crypto Library for my API(s)

I've begun working on a little crypto library that will allow for some abstracted cryptography, so that the API methods will be free of low-level crypto-code. Here are the main features it will have:
- `ServerKey` struct that handles encryption, decryption, and authentication using a few easy-to-use methods
  - `decrypt_request()`: decrypts a request and initializes a `ServerKey` instance
  - `verify_signature()`
  - `encrypt_and_sign()`: takes an instance of a protocol buffer, encrypts it, zeroizes it, packages it into an HTTP response, then signs it
  - `database_key()`: generates a key to be used for encrypting/decrypting some data going into/from the database
    - this might get abstracted to `.encrypt_db()` and `.decrypt_db()`.

This is what needs to be done
- [ ] use `rand_chacha` with `zeroize` instead of `OsRng` or `StdRng`
- [x]  try to switch from `openssl` to `RustCrypto`
- [x] use `p384` instead of `RSA`
- [ ] use automagically rotating keys, and an API method that updates a webpage containing the latest keys
- [ ] use a more standard encryption method for interactions with the database, and use unique encryption keys for each client
- [ ] switch from `serde_json` to `prost` for serializing data structures that contain secret information 
    - `serde_json` can make unzeroize-able copies of data, and the only way to zeroize them would be to create a custom deallocator. It would be better to just use protocol buffers instead
- [x]  zeroize sensitive data
- [x] use HMACs to invalidate bad requests
- [ ] consider trying to mitigate side channel timing attacks/Oracle attacks that try to manipulate the HMAC
    - this might be difficult to do without spending extra money on database calls

### Existing API

- [ ]  migrate the API methods with the crypto library
- [ ] clean up the nasty code
- [ ] test the library
- [ ] ensure the API is reachable with my custom domain name instead of the generic endpoint
- [ ] revisit the AWS security policies regarding the endpoints

### Update WordPress Plugin

- [ ] switch to protocol buffers
- [ ] switch to `p384`
- [ ] authenticate the service's public keys with the SSL certificate to prevent an Adversary in the Middle Attack

### Update C++ client-side code

- [ ] Switch from JUCE's "RSA" public/private key encryption to `p384` using `openssl` or `libsodium`
  - RSA is really slow, and also... JUCE's "RSA" technically isn't RSA. Not only that, but the encryption algorithm as suggested in their library is *not constant-time*, meaning that anyone using the standard JUCE RSA encryption (without using proven constant-time operations) could be vulnerable to timing attacks. Instead of conforming to the JUCE RSA encryption and simply switching to constant-time operations, I will just switch to a more-standard `p384`, which should be incredibly fast, incredibly strong, and incredibly cheaper... you don't usually get those 3 characteristics all at once.
- [ ] Update the UI for the license activation
- [ ] Allow licenses to be activated using an activation file
- [ ] Ensure that the crypto code doesn't compile into a separate `.dll`. This would be bad if end users are able to delete the DRM binaries.
